name: Actions_Pipeline

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Installing packages
        run: cd ${{ github.workspace }}/angular && npm install

#      - name: Run test
#        run: cd ${{ github.workspace }}/angular && npm run test
#      - name: Error
#        if: failure()
#        run: exit 1

      - name: ng build
        run: cd ${{ github.workspace }}/angular && npm run build

      - name: Build Docker image
        run: sudo docker build . -t image

#      - name: Email
