name: Actions_Pipeline

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

env:
  IMAGE_NAME: image-angular

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Installing packages Angular
        run: cd ${{ github.workspace }}/angular && npm install
      - name: Installing packages React
        run: cd ${{ github.workspace }}/react && npm install

#      - name: Run test
#        run: cd ${{ github.workspace }}/angular && npm run test
#      - name: Error
#        if: failure()
#        run: exit 1

      - name: ng build
        run: cd ${{ github.workspace }}/angular && npm run build

      - name: Build Docker image
        run: sudo docker build . -t $IMAGE_NAME

      - name: Post image to github packages
        run: |
          IMAGE_ID=ghcr.io/krawczowakris/$IMAGE_NAME
          VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION


#      - name: Email
