name: Actions_Pipeline

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

env:
  IMAGE_NAME: image-angular-react-starter

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Installing packages Angular
        run: cd ${{ github.workspace }}/angular && npm install
      - name: Installing packages React
        run: cd ${{ github.workspace }}/react && npm install

#      - name: Run test
#        run: cd ${{ github.workspace }}/angular && npm run test
#      - name: Error
#        if: failure()
#        run: exit 1

      - name: Build project
        run: cd ${{ github.workspace }}/angular && npm run build

      - name: Build Docker image
        run: sudo docker build . -t $IMAGE_NAME

      - name: Login to GitHub container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Post image to github packages
        run: |
          IMAGE_ID=ghcr.io/krawczowakris/$IMAGE_NAME
          VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Get pipeline execution time
        run: echo "Help me, pls. AAAAA"

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          body: "Complete!"
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: KrawczowaKris
#          body: Build job of ${{ github.repository }} completed successfully!

      - name: Send failure email
        if: failure()
        run: echo "kva-kva-kva-kva"






















