name: Actions_Pipeline

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

env:
  IMAGE_NAME: image-angular-react-starter
  GH_TOKEN: ${{ github.token }}

jobs:
  pipeline_of_build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Installing packages Angular
        run: cd ${{ github.workspace }}/angular && npm install
      - name: Installing packages React
        run: cd ${{ github.workspace }}/react && npm install

      - name: Run test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: cd ${{ github.workspace }}/angular && npm run test

      - name: Build project
        run: cd ${{ github.workspace }}/angular && npm run build

      - name: Build Docker image
        run: sudo docker build . -t $IMAGE_NAME

      - name: Login to GitHub container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Post image to github packages
        run: |
          IMAGE_ID=ghcr.io/krawczowakris/$IMAGE_NAME
          VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Send email about pipeline status
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: KrawczowaKris
          body: Build job of ${{ github.repository }} completed with status ${{ job.status }}

      - name: Get pipeline execution time
        run: echo "$(gh run list --workflow ci.yaml | head -n 1 | awk -F'\t' '{ print $8 }')"

      - name: Send email about pipeline execution time
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Pipeline execution time
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: KrawczowaKris
          body: Pipeline execution time
