name: Hello

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: echo "Hello"
      
